#!/usr/bin/env python3
import sys
import os.path
import sqlite3

def usage():
    print('Usage: %s <database file> show|prune' % sys.argv[0], file=sys.stderr)
    sys.exit(1)

if len(sys.argv) != 3:
    usage()

if sys.argv[2] == 'show':
    # open read-only. FIXME escape name
    connection = sqlite3.connect('file:%s?mode=ro' % sys.argv[1])
    result = connection.execute('SELECT printable_path, modified, read_size FROM hashed')
    for row in result.fetchall():
        print('%s %s %s' % row)
elif sys.argv[2] == 'prune':
    with sqlite3.connect(sys.argv[1]) as connection:
        cursor = connection.cursor()
        result = cursor.execute('SELECT path, printable_path FROM hashed')
        deleted = []
        for path, printable in result.fetchall():
            if not os.path.isfile(path):
                print('pruning %s' % printable)
                deleted.append((path,))
        if len(deleted) == 0:
            print('all files still exist')
        else:
            cursor.executemany('DELETE FROM hashed WHERE path = ?', deleted)
            print('pruned %d files' % cursor.rowcount)
else:
    usage()
